version: "3"
services:
  ruby:
    image: rguidpost
    build:
      context: .
      args:
        GIT_EMAIL: $GIT_EMAIL
        GIT_NAME: $GIT_NAME
    command: /bin/bash
    volumes:
      - .:/app
      - ~/.ssh:/root/ssh
    environment:
      BUNDLE_APP_CONFIG: /app/.bundle
